### ISSUE TITLE
Use TermsFilter or TermsQuery

### ISSUE THREAD

**Issue by prog8** [sematext/solr-redis#23]
SolrRedis plugin can use TermsFilter or even for better performance TermsQuery. This should improve the performance of SolrRedis plugin especially for large number of terms (elements in Redis data structures - eg. SET).

**Comment by lstrojny** [comment]
Will that help with the max boolean clauses limit as well?

**Comment by prog8** [comment]
Yes it will also help with that.

**Comment by lstrojny** [comment]
Any news?

**Comment by otisg** [comment]
@lstrojny we currently don't use Redis internally, so I doubt we'll do this without somebody's PR...

**Comment by lstrojny** [comment]
@otisg @prog8 any pointer where to look at?

**Comment by prog8** [comment]
Hi @lstrojny. You should just change BooleanQuery to org.apache.lucene.search.join.TermsQuery. This should be enough.

**Comment by lstrojny** [comment]
Thanks, will try that.

**Comment by smock** [comment]
I'd like to take this up, is the suggestion to migrate to TermsQuery in RedisQParser?

**Comment by otisg** [comment]
+1, yes, I think so @smock
