### ISSUE TITLE
support for solr 8.5.x

### ISSUE THREAD

**Issue by atomotic** [sematext/solr-redis#43]
could this plugin be updated to support solr 8.5.x?
my knowledge of java and solr internals are very limited  
i can see an import error here **src/main/java/com/sematext/solr/redis/RedisQParser.java**

`import org.apache.lucene.queries.TermsQuery`

**Comment by otisg** [comment]
We could merge a PR if it doesn't break anything.

**Comment by radu-gheorghe** [comment]
@atomotic the [1.10.0](https://github.com/sematext/solr-redis/releases/tag/1.10.0) release supports Solr 8.6.0. Would that work for you?

I assume that you wanted a more recent release and that works => closing this issue. Feel free to reopen if not. I assume simply changing the dependency to 8.5.x will work.
